version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: finch
      POSTGRES_PASSWORD: finch123
      POSTGRES_DB: finchdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build: .
    container_name: finch_app
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/finchdb
      SPRING_DATASOURCE_USERNAME: finch
      SPRING_DATASOURCE_PASSWORD: finch123
      APP_JWT_SECRET: change-me-in-prod-please-32-bytes-minimum-aaaaaaaaaaaaaa
      APP_JWT_ISSUER: example-auth
      APP_JWT_EXPIRATION_MINUTES: 120
    ports:
      - "8080:8080"
