spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finchdb
    username: finch
    password: finch123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
    show-sql: true
    
  flyway:
    enabled: true
    locations: classpath:db/migration

  main:
    allow-circular-references: true

server:
  port: 8081

app:
  jwt:
    issuer: example-auth
    expiration-minutes: 120
    secret: "change-me-in-prod-please-32-bytes-minimum-aaaaaaaaaaaaaa"

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
